---
title: "Homework 3"
author: "Vanessa Dinh"
date: "10/12/22"
---

## Load tidyverse

```{r}
library(tidyverse)
```

## Problem 1

```{r}
library(p8105.datasets)
data("instacart")
```

## Problem 2

```{r}
accel = 
  read_csv("./data/accel_data.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    activity_1:activity_1440,
    names_to = "minute",
    names_prefix = "activity_",
    values_to = "activity_level"
  ) %>% 
  mutate(
    day_type = ifelse(
      day == "Saturday" | day == "Sunday",
      "Weekend", "Weekday"),
    week = as.integer(week),
    day_id = as.integer(day_id),
    day = factor(day, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")),
    day_type = as.factor(day_type),
    minute = as.integer(minute),
    activity_level = as.numeric(activity_level))

accel
str(accel)

# In the accel dataset, there are 3 integer variables: week, day_id, and minute. There are 2 factor variables: day and day_type (weekend/weekday variable), and activity level variable is numeric.
# There are 50,400 observations and 6 variables.
  
```

```{r}
summary_accel = accel %>%  
  group_by(week, day) %>% 
  summarize(total_activity = sum(activity_level)) %>% 
  pivot_wider(
    names_from = day,
    values_from = total_activity
  )

summary_accel

# There is less activity on Saturdays. Mondays, Fridays, Saturdays, and Sundays have variable activity while Tuesdays, Wednesdays, and Thursdays have similar total activity levels.
```

```{r fig.align = 'center'}
accel_plot = accel %>% 
  mutate(minute = as.numeric(minute)) %>% 
  ggplot(aes(x = minute, y = activity_level, color = day)) +
   geom_line(alpha = .7) +
  labs(
    title = "Daily Activity by Minute",
    x = "Minute of the Day",
    y = "Activity Level"
  ) +
  scale_x_continuous(
    breaks = c(0, 250, 500, 750, 1000, 1250, 1500), 
    labels = c("0", "250", "500", "750", "1000", "1250", "1500"))+
  guides(color = guide_legend(title = "Day of the Week")) 
  
  
accel_plot

# There's less activity between 0 and about 300 minutes. There are spikes of activity at different points of the day, particularly on Friday at around 1200-1300 minutes.
```

## Problem 3

```{r}
library(p8105.datasets)
data("ny_noaa")

ny_noaa
```

```{r}
ny_noaa_tidy = 
  ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(
    date,
    into = c("year", "month", "day"),
    sep = '-') %>% 
  mutate(
    year = as.factor(year),
    month = as.integer(month),
    month = month.name[month],
    month = as.factor(month),
    station = as.factor(id),
    day = as.integer(day),
    prcp = as.numeric(prcp),
    snow = as.numeric(snow),
    snwd = as.numeric(snwd),
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin),
    prcp = prcp/10,
    tmax= tmax/10,
    tmin = tmin/10
  ) %>% 
  select(-id)

str(ny_noaa_tidy)

mode = function(v){
  uniqv = unique(v[!is.na(v)])
  uniqv[which.max(table(match(v, uniqv)))]
}

ny_noaa_snow = ny_noaa_tidy %>% 
  group_by(month) %>% 
  summarize(snow_mode = mode(snow))

# 0 is the most commonly observed value since snowfall is limited to less than half the year in the winter/late fall in New York.
```

```{r}
ny_noaa_plot = 
  ny_noaa_tidy %>% 
  group_by(station, year, month) %>% 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE))

```

```{r fig.align = 'center', fig.height = 8}
jan_july_plot =
  ny_noaa_plot %>% 
  filter(month == "January" | month == "July") %>% 
  ggplot(aes(x = year, y = mean_tmax, group = station, color = station)) +
  geom_line() +
  facet_wrap(~ month, ncol = 1) +
  theme(legend.position = "none") +
  labs(
    title = "Average Maximum Temperature in January and July by Year and NY Weather Station",
    x = "Year",
    y = "Average Maximum Temperature in Celsius"
  ) +
  viridis::scale_color_viridis(
    name = "station", 
    discrete = TRUE
  ) +
  scale_x_discrete(guide = guide_axis(angle = 45))

jan_july_plot

# Max temperatures in July are on average around 25 degrees Celsius higher than max temperatures in January. The max temperature seems to oscillate year to year, though it seems to become less variable between stations in the years 2000-2010.
```

```{r}
library(patchwork)
```

```{r}
tmax_tmin_ggplot = 
  ny_noaa_tidy %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex() +
  labs(
    title = "Minimum vs Maximum Temperature in Celsius in NY",
    x = "Minimum Temperature (Celsius)",
    y = "Maximum Temperature (Celsius)"
  ) +
  scale_y_continuous(
    breaks = c(-40, -20, 0, 20, 40, 60), 
    labels = c("-40 C", "-20 C", "0 C", "20 C", "40 C", "60 C")) +
  scale_x_continuous(
    breaks = c(-60, -40, -20, 0, 20, 40, 60), 
    labels = c("-60 C", "-40 C", "-20 C", "0 C", "20 C", "40 C", "60 C"))
  
```

```{r}
snowfall_plot = 
  ny_noaa_tidy %>% 
  filter(snow > 0 & snow < 100) %>% 
  ggplot(aes(x = snow, group = year, color = year)) +
  geom_density(alpha = 0.5) +
  labs(
    title = "Snowfall Distribution by Year",
    x = "Snowfall (mm)",
    y = "Density"
  )

```

```{r fig.align = 'center', fig.height = 8}
tmax_tmin_ggplot / snowfall_plot
```

